#!/bin/bash
BLACK="\e[30m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
WHITE="\e[37m"
large="\e#3"
BOLD="\e[1m"
neofetch
echo -e "ㅤ"
echo -e "ㅤ"
echo -e "ㅤ"
echo -e "ㅤ"
echo -e "ㅤ"
echo -e "ㅤ"
echo -e "ㅤ"

echo -e "${YELLOW} - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "
echo -e "${BOLD}${GREEN}Powered By"
echo -e "${RED}Egg provided by : Apex.cloud©️ Company 🌟"
echo "VPS motorcyles._ egg made by: czo (Jake)"
echo -e "${YELLOW} - - - - - - - - - - - - - - - - ${WHITE}[ ${BOLD}${GREEN}TYPE YOUR COMMAND ${WHITE}]${YELLOW} - - - - - - - - - - - - - - "
